"use client";

import React, { useState, useEffect, useCallback } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import TwoPanelSidebar from "./TwoPanelSidebar";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Share2,
  History,
  BookOpen,
  Check,
  Copy,
  PanelLeftOpen,
  PanelLeftClose,
  Zap,
  FolderOpen,
  Settings,
  Globe,
  Search,
  Plus,
  X,
  Moon,
  Sun,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Pencil,
  Send,
  Trash2,
  Loader2,
  MoreHorizontal,
  FileText,
  Edit,
  Upload,
  Download,
  FileUp,
  FileDown,
  Columns,
  SplitSquareHorizontal,
  Import,
} from "lucide-react";
import { useTheme } from "@/contexts/ThemeContext";
import { useAuth } from "@/contexts/AuthContext";
import { useCollections } from "@/contexts/CollectionsContext";
import { getThemeClasses, getMethodColors } from "@/lib/theme";
import RequestPanel from "./RequestPanel";
import ResponsePanel from "./ResponsePanel";
import { generateShareableUrl, getSharedRequest } from "@/lib/share-encoding";
import { saveToHistory } from "@/lib/storage";
import {
  processRequestWithVariables,
  getEnvironments,
  getActiveEnvironment,
  setActiveEnvironment,
  createEnvironment,
  updateEnvironment,
  deleteEnvironment,
  getActiveVariables,
  addVariableToEnvironment,
  updateVariableInEnvironment,
  deleteVariableFromEnvironment,
} from "@/lib/environments";
import { generateRequestName, isAutoGeneratedName } from "@/lib/request-utils";
import DocGeneratorModal from "@/components/docs/DocGeneratorModal";
import SearchInput from "@/components/ui/SearchInput";
import ImportModal from "@/components/modals/ImportModal";
import ExportModal from "@/components/modals/ExportModal";
import CreateEnvironmentModal from "@/components/modals/CreateEnvironmentModal";
import AddVariableModal from "@/components/modals/AddVariableModal";
import EditVariableModal from "@/components/modals/EditVariableModal";
import SettingsModal from "@/components/modals/SettingsModal";
import CreateCollectionModal from "@/components/modals/CreateCollectionModal";
import SaveToCollectionModal from "@/components/modals/SaveToCollectionModal";
import DashboardHeader from "../header/DashboardHeader";
import { sidebarMenuItems } from "@/config/sidebar";

export default function Playground() {
  const { toggleTheme, isDark } = useTheme();
  const { user, signOut, loading: authLoading } = useAuth();
  const {
    collections,
    activeCollectionId,
    setActiveCollectionId,
    addRequestToCollection,
    updateRequestInCollection,
    saveToHistory,
    createCollection,
    deleteCollection,
    getCollectionsWithDocs,
    loading: collectionsLoading,
  } = useCollections();
  const themeClasses = getThemeClasses(isDark);
  // Request tabs state - will be restored from localStorage if available
  const [requestTabs, setRequestTabs] = useState([]);
  const [activeTabId, setActiveTabId] = useState(null);
  const [tabsInitialized, setTabsInitialized] = useState(false);

  const [shareUrl, setShareUrl] = useState("");
  const [showShared, setShowShared] = useState(false);
  const [shareDialogOpen, setShareDialogOpen] = useState(false);
  const [copySuccess, setCopySuccess] = useState(false);
  const [sidebarCollapsed, setSidebarCollapsed] = useState(
    typeof window !== "undefined" && window.innerWidth < 1024
  );
  const [activeMenuTab, setActiveMenuTab] = useState("collections");
  const [sidebarContentOpen, setSidebarContentOpen] = useState(true); // Track if sidebar content is visible
  const [sidebarContentWidth, setSidebarContentWidth] = useState(280); // Width of the content panel in pixels
  const [isSidebarResizing, setIsSidebarResizing] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  const [searchModalOpen, setSearchModalOpen] = useState(false);

  // Handle search modal keyboard shortcuts and clicks
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === "Escape" && searchModalOpen) {
        setSearchModalOpen(false);
        setSearchQuery("");
      }
    };

    const handleClickOutside = (e) => {
      if (searchModalOpen && !e.target.closest(".search-container")) {
        setSearchModalOpen(false);
      }
    };

    document.addEventListener("keydown", handleKeyDown);
    document.addEventListener("mousedown", handleClickOutside);

    return () => {
      document.removeEventListener("keydown", handleKeyDown);
      document.removeEventListener("mousedown", handleClickOutside);
    };
  }, [searchModalOpen]);
  const [editingRequestName, setEditingRequestName] = useState(false);
  const [layoutMode, setLayoutMode] = useState("single"); // 'single' or 'split'
  const [requestPanelWidth, setRequestPanelWidth] = useState(50); // percentage
  const [requestPanelHeight, setRequestPanelHeight] = useState(35); // percentage for single column
  const [isDragging, setIsDragging] = useState(false);

  // Drag handling functions for resizable panels (must be at top level)
  const handleMouseDown = (e) => {
    setIsDragging(true);
    e.preventDefault();
  };

  const handleMouseMove = useCallback(
    (e) => {
      if (isDragging) {
        const container = document.querySelector("[data-layout-container]");
        if (container) {
          const containerRect = container.getBoundingClientRect();

          if (layoutMode === "split") {
            // Horizontal dragging for split layout
            const newWidth =
              ((e.clientX - containerRect.left) / containerRect.width) * 100;
            setRequestPanelWidth(Math.min(Math.max(newWidth, 20), 80)); // Limit between 20% and 80%
          } else {
            // Vertical dragging for single column layout
            const newHeight =
              ((e.clientY - containerRect.top) / containerRect.height) * 100;
            setRequestPanelHeight(Math.min(Math.max(newHeight, 20), 80)); // Limit between 20% and 80%
          }
        }
      }
    },
    [isDragging, layoutMode]
  );

  const handleMouseUp = () => {
    setIsDragging(false);
  };

  // Sidebar resize handlers
  const handleSidebarResizeStart = (e) => {
    setIsSidebarResizing(true);
    e.preventDefault();
    e.stopPropagation();
  };

  const handleSidebarResizeMove = useCallback(
    (e) => {
      if (isSidebarResizing) {
        const sidebar = document.querySelector("[data-sidebar-container]");
        if (sidebar) {
          const sidebarRect = sidebar.getBoundingClientRect();
          // Calculate new width: mouse position - sidebar left - navigation panel width (100px)
          const newWidth = e.clientX - sidebarRect.left - 100;
          // Apply constraints: min 150px, max 400px
          const constrainedWidth = Math.min(Math.max(newWidth, 150), 400);
          setSidebarContentWidth(constrainedWidth);
        }
      }
    },
    [isSidebarResizing]
  );

  const handleSidebarResizeEnd = () => {
    setIsSidebarResizing(false);
  };

  // Handle navigation item clicks with toggle behavior
  const router = useRouter();

  const handleNavItemClick = (itemId) => {
    if (itemId === "documentation") {
      // Navigate to documentation page
      router.push("/docs");
      return;
    }

    if (activeMenuTab === itemId && sidebarContentOpen) {
      // If clicking the same active tab and content is open, close it
      setSidebarContentOpen(false);
    } else {
      // If clicking a different tab or content is closed, open/switch to it
      setActiveMenuTab(itemId);
      setSidebarContentOpen(true);
    }
  };

  // Effect to handle mouse events (must be at top level)
  useEffect(() => {
    if (isDragging) {
      document.addEventListener("mousemove", handleMouseMove);
      document.addEventListener("mouseup", handleMouseUp);
      return () => {
        document.removeEventListener("mousemove", handleMouseMove);
        document.removeEventListener("mouseup", handleMouseUp);
      };
    }
  }, [isDragging, handleMouseMove]);

  // Effect to handle sidebar resize events
  useEffect(() => {
    if (isSidebarResizing) {
      document.addEventListener("mousemove", handleSidebarResizeMove);
      document.addEventListener("mouseup", handleSidebarResizeEnd);
      return () => {
        document.removeEventListener("mousemove", handleSidebarResizeMove);
        document.removeEventListener("mouseup", handleSidebarResizeEnd);
      };
    }
  }, [isSidebarResizing, handleSidebarResizeMove]);

  // Collections state
  const [expandedCollections, setExpandedCollections] = useState(
    new Set(["my-api-tests"])
  ); // Default expanded
  const [editingCollection, setEditingCollection] = useState(null);
  const [editingRequest, setEditingRequest] = useState(null);

  // Modal states
  const [docsModalOpen, setDocsModalOpen] = useState(false);
  const [selectedCollectionForDocs, setSelectedCollectionForDocs] =
    useState(null);
  const [settingsModalOpen, setSettingsModalOpen] = useState(false);
  const [createCollectionDialogOpen, setCreateCollectionDialogOpen] =
    useState(false);
  const [saveToCollectionModalOpen, setSaveToCollectionModalOpen] =
    useState(false);
  const [pendingRequestToSave, setPendingRequestToSave] = useState(null);

  // Environments state
  const [expandedEnvironments, setExpandedEnvironments] = useState(new Set());

  const toggleEnvironment = (envId) => {
    setExpandedEnvironments((prev) => {
      const newSet = new Set(prev);
      if (newSet.has(envId)) {
        newSet.delete(envId);
      } else {
        newSet.add(envId);
      }
      return newSet;
    });
  };

  const handleCreateEnvironment = async ({ name, description }) => {
    try {
      const newEnv = createEnvironment(name, []);
      setEnvironments((prev) => ({ ...prev, [newEnv.id]: newEnv }));
      setNewEnvironmentColor("blue");
    } catch (error) {
      console.error("Failed to create environment:", error);
    }
  };

  const handleDeleteEnvironment = async (envId) => {
    try {
      const updatedEnvironments = deleteEnvironment(envId);
      setEnvironments(updatedEnvironments);
      if (activeEnvironmentId === envId) {
        setActiveEnvironmentId("development");
      }
    } catch (error) {
      console.error("Failed to delete environment:", error);
    }
  };

  const handleEnvironmentSelect = (envId) => {
    setActiveEnvironment(envId);
    setActiveEnvironmentId(envId);
  };

  const handleAddVariable = (envId) => {
    setSelectedEnvironmentForVariable(envId);
    setAddVariableDialogOpen(true);
  };

  const handleEditVariable = (envId, variableIndex, variable) => {
    setSelectedEnvironmentForVariable(envId);
    setSelectedVariableIndex(variableIndex);
    setEditVariableDialogOpen(true);
  };

  const handleSaveNewVariable = async (envId, variable) => {
    try {
      const updatedEnv = addVariableToEnvironment(envId, variable);
      setEnvironments((prev) => ({ ...prev, [updatedEnv.id]: updatedEnv }));
    } catch (error) {
      console.error("Failed to add variable:", error);
    }
  };

  const handleSaveEditedVariable = async (envId, variableIndex, variable) => {
    try {
      const updatedEnv = updateVariableInEnvironment(
        envId,
        variableIndex,
        variable
      );
      setEnvironments((prev) => ({ ...prev, [updatedEnv.id]: updatedEnv }));
      setSelectedVariableIndex(null);
    } catch (error) {
      console.error("Failed to update variable:", error);
    }
  };

  const handleDeleteVariable = async (envId, variableIndex) => {
    try {
      const updatedEnv = deleteVariableFromEnvironment(envId, variableIndex);
      setEnvironments((prev) => ({ ...prev, [updatedEnv.id]: updatedEnv }));
    } catch (error) {
      console.error("Failed to delete variable:", error);
    }
  };
  const [editingEnvironment, setEditingEnvironment] = useState(null);

  // Request history state
  const [historyItems, setHistoryItems] = useState([]);
  const [historyLoading, setHistoryLoading] = useState(false);
  const [historySearchQuery, setHistorySearchQuery] = useState("");

  // Load request history when user changes or when history tab is active
  useEffect(() => {
    if (user && activeMenuTab === "history") {
      loadRequestHistory();
    } else if (!user) {
      setHistoryItems([]);
    }
  }, [user, activeMenuTab]);

  const loadRequestHistory = async () => {
    setHistoryLoading(true);
    try {
      const { getRequestHistory } = await import("@/lib/supabase-collections");
      const history = await getRequestHistory(50); // Get last 50 requests

      // Transform the data to match our UI format
      const transformedHistory = history.map((item) => ({
        id: item.id,
        name: generateRequestName(item.method, item.url),
        method: item.method,
        url: item.url,
        headers: item.headers,
        body: item.body,
        timestamp: formatTimeAgo(new Date(item.created_at)),
        status: item.response_status,
        responseTime: item.response_time,
        createdAt: item.created_at,
        responseHeaders: item.response_headers,
        responseBody: item.response_body,
      }));

      setHistoryItems(transformedHistory);
    } catch (error) {
      console.error("Failed to load request history:", error);
    } finally {
      setHistoryLoading(false);
    }
  };

  // Helper function to format time ago
  const formatTimeAgo = (date) => {
    const now = new Date();
    const diffInMinutes = Math.floor((now - date) / (1000 * 60));

    if (diffInMinutes < 1) return "Just now";
    if (diffInMinutes < 60) return `${diffInMinutes} min ago`;

    const diffInHours = Math.floor(diffInMinutes / 60);
    if (diffInHours < 24)
      return `${diffInHours} hour${diffInHours > 1 ? "s" : ""} ago`;

    const diffInDays = Math.floor(diffInHours / 24);
    return `${diffInDays} day${diffInDays > 1 ? "s" : ""} ago`;
  };

  // Filter history items based on search
  const filteredHistoryItems = historyItems.filter((item) => {
    if (!historySearchQuery.trim()) return true;
    const query = historySearchQuery.toLowerCase();
    return (
      item.name.toLowerCase().includes(query) ||
      item.method.toLowerCase().includes(query) ||
      item.url.toLowerCase().includes(query)
    );
  });

  // Calculate history analytics
  const historyAnalytics = {
    total: historyItems.length,
    successful: historyItems.filter(
      (item) => item.status >= 200 && item.status < 300
    ).length,
    failed: historyItems.filter((item) => item.status >= 400).length,
    avgResponseTime:
      historyItems.length > 0
        ? Math.round(
            historyItems.reduce(
              (acc, item) => acc + (item.responseTime || 0),
              0
            ) / historyItems.length
          )
        : 0,
    methods: historyItems.reduce((acc, item) => {
      acc[item.method] = (acc[item.method] || 0) + 1;
      return acc;
    }, {}),
    recentActivity: historyItems.slice(0, 5),
  };

  // Replay request from history
  const replayHistoryRequest = (historyItem) => {
    // Create a new tab with the request from history
    const newTabId = Date.now().toString();
    const newTab = {
      id: newTabId,
      name: historyItem.name + " (Replay)",
      request: {
        method: historyItem.method,
        url: historyItem.url,
        headers: historyItem.headers || {},
        body: historyItem.body || "",
      },
      response: null,
      loading: false,
      collectionRequestId: null,
      isModified: false,
    };

    setRequestTabs((prev) => [...prev, newTab]);
    setActiveTabId(newTabId);

    console.log("Replayed request from history:", historyItem.name);
  };

  // Clear request history
  const clearHistory = async () => {
    if (window.confirm("Are you sure you want to clear all request history?")) {
      setHistoryItems([]);
      // TODO: Add actual database clearing if needed
      console.log("Request history cleared");
    }
  };

  // Environment management state
  const [environments, setEnvironments] = useState({});
  const [activeEnvironmentId, setActiveEnvironmentId] = useState("development");
  const [createEnvironmentDialogOpen, setCreateEnvironmentDialogOpen] =
    useState(false);
  const [editingEnvironmentVariable, setEditingEnvironmentVariable] =
    useState(null);
  const [addVariableDialogOpen, setAddVariableDialogOpen] = useState(false);
  const [editVariableDialogOpen, setEditVariableDialogOpen] = useState(false);
  const [selectedEnvironmentForVariable, setSelectedEnvironmentForVariable] =
    useState(null);
  const [selectedVariableIndex, setSelectedVariableIndex] = useState(null);
  const [newEnvironmentColor, setNewEnvironmentColor] = useState("blue");

  // Load environments on mount
  useEffect(() => {
    const loadedEnvironments = getEnvironments();
    setEnvironments(loadedEnvironments);
    setActiveEnvironmentId(getActiveEnvironment());
  }, []);

  // Get environments as array for display
  const environmentsArray = Object.values(environments);

  // Sample trash data
  const trashItems = [
    {
      id: "trash-1",
      name: "Old API Collection",
      type: "collection",
      deletedAt: "2 days ago",
    },
    {
      id: "trash-2",
      name: "Test Request",
      type: "request",
      method: "DELETE",
      deletedAt: "1 week ago",
    },
  ];

  // Collection management functions
  const toggleCollection = (collectionId) => {
    const newExpanded = new Set(expandedCollections);
    if (newExpanded.has(collectionId)) {
      newExpanded.delete(collectionId);
    } else {
      newExpanded.add(collectionId);
    }
    setExpandedCollections(newExpanded);
  };

  // Environment management functions

  // Helper functions for tab management
  const getCurrentTab = () => requestTabs.find((tab) => tab.id === activeTabId);

  const updateCurrentTab = (updates) => {
    setRequestTabs((tabs) =>
      tabs.map((tab) =>
        tab.id === activeTabId ? { ...tab, ...updates, isModified: true } : tab
      )
    );
  };

  const createNewTab = () => {
    const newTabId = Date.now().toString();
    const newTab = {
      id: newTabId,
      name: "Untitled Request",
      request: {
        method: "GET",
        url: "",
        headers: {},
        body: "",
      },
      response: null,
      loading: false,
      collectionRequestId: null,
      isModified: false,
    };
    setRequestTabs((tabs) => [...tabs, newTab]);
    setActiveTabId(newTabId);
  };

  const closeTab = (tabId) => {
    if (requestTabs.length === 1) return; // Don't close the last tab

    setRequestTabs((tabs) => {
      const newTabs = tabs.filter((tab) => tab.id !== tabId);
      // If we're closing the active tab, switch to the previous one
      if (tabId === activeTabId) {
        const activeIndex = tabs.findIndex((tab) => tab.id === tabId);
        const newActiveIndex = activeIndex > 0 ? activeIndex - 1 : 0;
        setActiveTabId(newTabs[newActiveIndex].id);
      }
      return newTabs;
    });
  };

  // Load shared request and active collection on mount
  useEffect(() => {
    const sharedRequest = getSharedRequest();
    if (sharedRequest) {
      updateCurrentTab({ request: sharedRequest });
      setShowShared(true);
      setTimeout(() => setShowShared(false), 3000);
    }

    // Load active collection
    const activeColId = activeCollectionId;
    setActiveCollectionId(activeColId);
  }, []);

  // Get current tab data
  const currentTab = getCurrentTab();
  const request = {
    method: "GET",
    url: "",
    headers: {},
    body: "",
    ...currentTab?.request,
  };
  const response = currentTab?.response || null;
  const loading = currentTab?.loading || false;

  const handleSaveRequest = () => {
    // Use the same logic as the keyboard shortcut - will show modal if needed
    saveCurrentRequestToCollection();
  };

  const executeRequest = async () => {
    updateCurrentTab({ loading: true });
    try {
      // Process request with environment variables
      const processedRequest = processRequestWithVariables(request);

      const options = {
        method: processedRequest.method,
        headers: {
          "Content-Type": "application/json",
          ...processedRequest.headers,
        },
      };

      if (processedRequest.method !== "GET" && processedRequest.body) {
        options.body = processedRequest.body;
      }

      const startTime = Date.now();
      const res = await fetch(processedRequest.url, options);
      const endTime = Date.now();

      const data = await res.text();
      let parsedData = data;

      try {
        parsedData = JSON.parse(data);
      } catch (e) {
        // Keep as text if not JSON
      }

      const responseData = {
        status: res.status,
        statusText: res.statusText,
        headers: Object.fromEntries(res.headers.entries()),
        data: parsedData,
        time: endTime - startTime,
        size: new Blob([data]).size,
      };

      updateCurrentTab({ response: responseData, loading: false });

      // Save to history (adjust format for database)
      const historyResponse = {
        ...responseData,
        body: responseData.data,
        responseTime: responseData.time,
      };
      saveToHistory(request, historyResponse);

      // Refresh history if user is viewing history tab
      if (activeMenuTab === "history") {
        loadRequestHistory();
      }
    } catch (error) {
      const errorResponse = {
        error: error.message,
        status: 0,
        time: 0,
      };

      updateCurrentTab({ response: errorResponse, loading: false });

      // Save failed requests to history too (adjust format for database)
      const historyErrorResponse = {
        ...errorResponse,
        body: errorResponse.error,
        responseTime: errorResponse.time,
      };
      saveToHistory(request, historyErrorResponse);

      // Refresh history if user is viewing history tab
      if (activeMenuTab === "history") {
        loadRequestHistory();
      }
    }
  };

  const handleShare = () => {
    const url = generateShareableUrl(request);
    if (url) {
      setShareUrl(url);
      setShareDialogOpen(true);
    }
  };

  const copyShareUrl = async () => {
    try {
      await navigator.clipboard.writeText(shareUrl);
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    } catch (err) {
      console.error("Failed to copy to clipboard:", err);
    }
  };

  const handleCreateCollection = async (collectionName) => {
    try {
      console.log("Creating collection:", collectionName);
      await createCollection(collectionName, "", "blue");
    } catch (err) {
      console.error("Failed to create collection:", err);
    }
  };

  const handleDeleteCollection = async (collectionId, collectionName) => {
    if (
      window.confirm(
        `Are you sure you want to delete "${collectionName}"? This will also delete all requests in this collection.`
      )
    ) {
      try {
        console.log("Deleting collection:", collectionId);
        await deleteCollection(collectionId);
      } catch (err) {
        console.error("Failed to delete collection:", err);
      }
    }
  };

  const handleCreateRequest = async (collectionId) => {
    try {
      console.log("Creating new request in collection:", collectionId);

      // Create a new request object
      const newRequest = {
        name: "Untitled Request",
        description: "",
        method: "GET",
        url: "",
        headers: {},
        body: "",
        tags: [],
      };

      // Add the request to the collection in the database
      const savedRequest = await addRequestToCollection(
        collectionId,
        newRequest
      );

      // Create a new tab with this request
      const newTabId = Date.now().toString();
      const newTab = {
        id: newTabId,
        name: savedRequest.name,
        request: {
          method: savedRequest.method,
          url: savedRequest.url,
          headers: savedRequest.headers || {},
          body: savedRequest.body || "",
        },
        response: null,
        loading: false,
        collectionRequestId: savedRequest.id,
        isModified: false,
      };

      // Add the new tab and make it active
      setRequestTabs((prev) => [...prev, newTab]);
      setActiveTabId(newTabId);

      // Expand the collection to show the new request
      setExpandedCollections((prev) => new Set(prev).add(collectionId));

      console.log("New request created and tab opened:", savedRequest);
    } catch (err) {
      console.error("Failed to create request:", err);
    }
  };

  const handleEditCollection = (collectionId) => {
    setEditingCollection(collectionId);
  };

  const handleDuplicateCollection = async (collection) => {
    try {
      console.log("Duplicating collection:", collection.name);
      const duplicatedName = `${collection.name} Copy`;
      await createCollection(
        duplicatedName,
        collection.description,
        collection.color
      );
      // TODO: Also duplicate the requests in the collection
    } catch (err) {
      console.error("Failed to duplicate collection:", err);
    }
  };

  const handleRequestClick = (request) => {
    console.log("Opening request in new tab:", request.name);

    // Check if request is already open in a tab
    const existingTab = requestTabs.find(
      (tab) => tab.collectionRequestId === request.id
    );

    if (existingTab) {
      // If tab exists, just switch to it
      setActiveTabId(existingTab.id);
      return;
    }

    // Create a new tab with this request
    const newTabId = Date.now().toString();
    const newTab = {
      id: newTabId,
      name: request.name,
      request: {
        method: request.method,
        url: request.url,
        headers: request.headers || {},
        body: request.body || "",
      },
      response: null,
      loading: false,
      collectionRequestId: request.id,
      isModified: false,
    };

    // Add the new tab and make it active
    setRequestTabs((prev) => [...prev, newTab]);
    setActiveTabId(newTabId);
  };

  // Request modification handlers
  const setRequest = (newRequest) => {
    const currentTab = getCurrentTab();
    const updates = { request: newRequest, isModified: true };

    // Auto-update name if it's auto-generated and URL or method changed
    if (
      currentTab &&
      currentTab.request &&
      isAutoGeneratedName(currentTab.name)
    ) {
      const urlChanged = currentTab.request.url !== newRequest.url;
      const methodChanged = currentTab.request.method !== newRequest.method;

      if (urlChanged || methodChanged) {
        const newName = generateRequestName(newRequest.method, newRequest.url);
        updates.name = newName;
        console.log("Auto-updating request name:", newName);
      }
    }

    updateCurrentTab(updates);
  };

  const setCurrentRequestName = (name) => {
    updateCurrentTab({ name, isModified: true });
  };

  // Function to get breadcrumb path for current request
  const getBreadcrumbPath = () => {
    const currentTab = requestTabs.find((tab) => tab.id === activeTabId);
    if (!currentTab?.collectionRequestId) {
      return null;
    }

    // Find the collection that contains this request
    for (const [collectionId, collection] of Object.entries(collections)) {
      const request = collection.requests?.find(
        (req) => req.id === currentTab.collectionRequestId
      );
      if (request) {
        return {
          collection: collection.name,
          request: request.name || currentTab.name,
        };
      }
    }
    return null;
  };

  // Auto-save request changes to collection
  const saveCurrentRequestToCollection = async () => {
    const currentTab = requestTabs.find((tab) => tab.id === activeTabId);
    if (!currentTab || !currentTab.request) {
      return;
    }

    // If request has no collection association, show the save modal
    if (!currentTab.collectionRequestId) {
      setPendingRequestToSave(currentTab);
      setSaveToCollectionModalOpen(true);
      return;
    }

    // If not modified, no need to save
    if (!currentTab.isModified) {
      return;
    }

    try {
      // Find which collection this request belongs to
      let collectionId = null;
      for (const [colId, collection] of Object.entries(collections)) {
        if (
          collection.requests?.some(
            (req) => req.id === currentTab.collectionRequestId
          )
        ) {
          collectionId = colId;
          break;
        }
      }

      if (!collectionId) {
        throw new Error("Could not find collection for this request");
      }

      const updatedRequest = {
        name: currentTab.name,
        method: currentTab.request?.method || "GET",
        url: currentTab.request?.url || "",
        headers: currentTab.request?.headers || {},
        body: currentTab.request?.body || "",
      };

      await updateRequestInCollection(
        collectionId,
        currentTab.collectionRequestId,
        updatedRequest
      );

      // Mark as saved
      updateCurrentTab({ isModified: false });

      console.log("Request saved to collection");
    } catch (err) {
      console.error("Failed to save request to collection:", err);
    }
  };

  // Handle saving request to selected collection
  const handleSaveToCollection = async (collectionId) => {
    if (!pendingRequestToSave) return;

    try {
      // Generate a better name if the current one is auto-generated or empty
      let requestName = pendingRequestToSave.name || "Untitled Request";
      if (
        isAutoGeneratedName(requestName) &&
        pendingRequestToSave.request?.url
      ) {
        requestName = generateRequestName(
          pendingRequestToSave.request.method,
          pendingRequestToSave.request.url
        );
      }

      const requestData = {
        name: requestName,
        description: "",
        method: pendingRequestToSave.request?.method || "GET",
        url: pendingRequestToSave.request?.url || "",
        headers: pendingRequestToSave.request?.headers || {},
        body: pendingRequestToSave.request?.body || "",
        tags: [],
      };

      const savedRequest = await addRequestToCollection(
        collectionId,
        requestData
      );

      // Update the tab to link it to the saved request and update name
      setRequestTabs((prev) =>
        prev.map((tab) =>
          tab.id === pendingRequestToSave.id
            ? {
                ...tab,
                name: savedRequest.name,
                collectionRequestId: savedRequest.id,
                isModified: false,
              }
            : tab
        )
      );

      // Close modal and clear pending request
      setSaveToCollectionModalOpen(false);
      setPendingRequestToSave(null);

      console.log("Request saved to collection:", savedRequest);
    } catch (err) {
      console.error("Failed to save request to collection:", err);
    }
  };

  // Save tabs to localStorage whenever they change (but only after initialization)
  useEffect(() => {
    if (tabsInitialized && requestTabs.length > 0) {
      const tabsToSave = {
        tabs: requestTabs,
        activeTabId: activeTabId,
        timestamp: Date.now(),
      };
      localStorage.setItem("api-playground-tabs", JSON.stringify(tabsToSave));
      console.log("Tabs saved to localStorage:", tabsToSave);
    }
  }, [requestTabs, activeTabId, tabsInitialized]);

  // Restore tabs from localStorage on component mount
  useEffect(() => {
    let restored = false;

    try {
      const savedTabsData = localStorage.getItem("api-playground-tabs");
      if (savedTabsData) {
        const {
          tabs,
          activeTabId: savedActiveTabId,
          timestamp,
        } = JSON.parse(savedTabsData);

        // Only restore if data is less than 7 days old
        const sevenDaysInMs = 7 * 24 * 60 * 60 * 1000;
        if (
          timestamp &&
          Date.now() - timestamp < sevenDaysInMs &&
          tabs &&
          tabs.length > 0
        ) {
          console.log("Restoring tabs from localStorage:", {
            tabs,
            savedActiveTabId,
          });
          setRequestTabs(tabs);
          if (
            savedActiveTabId &&
            tabs.some((tab) => tab.id === savedActiveTabId)
          ) {
            setActiveTabId(savedActiveTabId);
          } else {
            setActiveTabId(tabs[0].id);
          }
          restored = true;
        } else {
          console.log(
            "Saved tabs are too old or invalid, removing from storage"
          );
          localStorage.removeItem("api-playground-tabs");
        }
      }
    } catch (err) {
      console.error("Failed to restore tabs from localStorage:", err);
      localStorage.removeItem("api-playground-tabs");
    }

    // If no tabs were restored, create a default tab
    if (!restored) {
      console.log("No saved tabs found, creating default tab");
      const defaultUrl = "https://jsonplaceholder.typicode.com/posts/1";
      const defaultTab = {
        id: "1",
        name: generateRequestName("GET", defaultUrl),
        request: {
          method: "GET",
          url: defaultUrl,
          headers: {},
          body: "",
        },
        response: null,
        loading: false,
        collectionRequestId: null,
        isModified: false,
      };
      setRequestTabs([defaultTab]);
      setActiveTabId("1");
    }

    setTabsInitialized(true);
  }, []); // Only run on mount

  // Keyboard shortcuts (Ctrl+S / Cmd+S for save, Ctrl+Enter / Cmd+Enter for send)
  useEffect(() => {
    const handleKeyDown = (e) => {
      if ((e.ctrlKey || e.metaKey) && e.key === "s") {
        e.preventDefault();
        saveCurrentRequestToCollection();
      }
      if ((e.ctrlKey || e.metaKey) && e.key === "Enter") {
        e.preventDefault();
        if (request.url && !loading) {
          executeRequest();
        }
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [activeTabId, requestTabs, request.url, loading]);

  // Don't render until tabs are initialized
  if (!tabsInitialized) {
    return (
      <div
        className={`min-h-screen flex items-center justify-center ${themeClasses.bg.primary}`}
      >
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-400 mx-auto mb-2"></div>
          <p className={`text-sm ${themeClasses.text.secondary}`}>Loading...</p>
        </div>
      </div>
    );
  }

  return (
    <>
      {/* Main Content Area */}
      <div
        className={`flex-1 flex flex-col ${
          sidebarCollapsed ? "lg:ml-0" : "lg:ml-0"
        } ml-0 lg:ml-0 w-full lg:w-auto`}
      >
        {/* Request Tabs - Flat Design */}
        <div
          className={`${themeClasses.bg.glass} border-b ${themeClasses.border.primary}`}
        >
          <div className="flex items-center px-2 py-0">
            <div className="flex items-center overflow-x-auto scrollbar-hide">
              {requestTabs.map((tab) => {
                const methodColors = getMethodColors(
                  tab.request?.method || "GET",
                  isDark
                );
                return (
                  <div
                    key={tab.id}
                    className={`flex items-center gap-1 px-1 py-[.7rem] cursor-pointer min-w-0 group transition-all duration-200 border-b-[1.5px] ${
                      tab.id === activeTabId
                        ? `${themeClasses.text.primary} border-gray-800 dark:border-gray-400`
                        : `${themeClasses.text.secondary} hover:${themeClasses.text.primary} border-transparent hover:border-gray-300`
                    }`}
                    onClick={() => setActiveTabId(tab.id)}
                  >
                    <div
                      className={`font-medium ${methodColors.text} flex-shrink-0 text-[0.65rem] leading-none italic tracking-tight`}
                    >
                      {tab.request?.method || "GET"}
                    </div>

                    <span
                      className={`text-[0.75rem] truncate min-w-0 max-w-32 ${
                        tab.isModified ? "italic" : ""
                      }`}
                    >
                      {tab.name || "Untitled"}
                      {tab.isModified && (
                        <span className={`${themeClasses.text.accent} ml-1`}>
                          •
                        </span>
                      )}
                    </span>
                    {requestTabs.length > 1 && (
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          closeTab(tab.id);
                        }}
                        className={`cursor-pointer h-4 w-4 opacity-0 group-hover:opacity-100 transition-all duration-200 rounded flex-shrink-0 flex items-center justify-center ${themeClasses.text.tertiary} hover:${themeClasses.text.primary}`}
                      >
                        <X className="h-3 w-3" />
                      </button>
                    )}
                  </div>
                );
              })}
              <button
                onClick={createNewTab}
                className={`h-8 w-8 transition-all duration-200 flex-shrink-0 flex items-center justify-center group ${themeClasses.button.ghost} ml-2`}
              >
                <Plus className="h-3 w-3 group-hover:scale-110 transition-transform" />
              </button>
            </div>
          </div>
        </div>

        {/* Request Name Header - Full Width */}
        <div
          className={`${themeClasses.border.primary} ${
            isDark ? "bg-gray-900/20" : "bg-gray-50/50"
          }`}
        >
          <div className="px-4 pt-3">
            <div className="flex flex-col sm:flex-row sm:items-center gap-3">
              <div className="flex items-center gap-3 flex-1 min-w-0">
                <div className="flex items-center gap-2 group flex-1 min-w-0">
                  {(() => {
                    const breadcrumb = getBreadcrumbPath();
                    return editingRequestName ? (
                      <div className="flex items-center gap-1 flex-1 min-w-0">
                        {breadcrumb && (
                          <>
                            <span className="text-sm text-gray-500 dark:text-gray-400 flex-shrink-0">
                              {breadcrumb.collection}
                            </span>
                            <ChevronRight className="h-3 w-3 text-gray-400 flex-shrink-0" />
                          </>
                        )}
                        <input
                          type="text"
                          value={currentTab?.name || ""}
                          onChange={(e) =>
                            setCurrentRequestName(e.target.value)
                          }
                          onBlur={() => setEditingRequestName(false)}
                          onKeyDown={(e) => {
                            if (e.key === "Enter") {
                              setEditingRequestName(false);
                            }
                          }}
                          placeholder="Untitled Request"
                          className={`text-sm font-medium bg-transparent border-none outline-none px-1 py-0.5 min-w-0 ${themeClasses.text.primary}`}
                          style={{
                            width: `${Math.max(
                              currentTab?.name?.length || 15,
                              15
                            )}ch`,
                          }}
                          autoFocus
                        />
                      </div>
                    ) : (
                      <div className="flex items-center gap-1 flex-1 min-w-0">
                        {breadcrumb && (
                          <>
                            <span className="text-vs text-gray-500 dark:text-gray-400 flex-shrink-0">
                              {breadcrumb.collection}
                            </span>
                            <ChevronRight className="h-3 w-3 text-gray-400 flex-shrink-0" />
                          </>
                        )}
                        <span
                          className={`text-vs font-medium ${themeClasses.text.primary} truncate cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-800 px-1 py-0.5 rounded transition-colors`}
                          onClick={() => setEditingRequestName(true)}
                        >
                          {currentTab?.name || "Untitled Request"}
                        </span>
                        <button
                          onClick={() => setEditingRequestName(true)}
                          className={`opacity-0 group-hover:opacity-100 p-1 rounded transition-all duration-200 flex-shrink-0 ${themeClasses.button.ghost}`}
                        >
                          <Pencil className="h-3 w-3" />
                        </button>
                      </div>
                    );
                  })()}
                </div>
              </div>
              <div className="flex items-center gap-2">
                {!currentTab?.collectionRequestId && (
                  <>
                    <span
                      className={`text-xs px-2 py-1 rounded-full border ${themeClasses.status.warning}`}
                    >
                      Unsaved
                    </span>
                    <button
                      onClick={handleSaveRequest}
                      className={`px-3 py-1.5 text-xs rounded text-white transition-all duration-200 hover:scale-105`}
                      style={{
                        backgroundColor: "#171717",
                        border: "none",
                      }}
                    >
                      {currentTab?.collectionRequestId ? "Update" : "Save"}
                    </button>
                  </>
                )}
              </div>
            </div>
          </div>
        </div>

        {/* Method + URL + Send Row - Full Width */}
        <div className={`${themeClasses.border.primary}`}>
          <div className="px-3 py-3">
            <div className="flex flex-col lg:flex-row items-stretch lg:items-center gap-3">
              {/* METHOD SELECT + URL INPUT + ENVIRONMENT ROW */}
              <div className="flex-1 min-w-0">
                {/* Unified Method + URL Input */}
                <div
                  className={`flex h-10 sm:h-11 rounded-md border backdrop-blur-sm overflow-hidden ${
                    isDark
                      ? "bg-gray-800 border-gray-600"
                      : "bg-white border-gray-300"
                  } focus-within:ring-2 focus-within:ring-blue-500 focus-within:border-transparent transition-all`}
                  style={{ borderRadius: "6px" }}
                >
                  {/* METHOD SELECT */}
                  <select
                    value={request.method}
                    onChange={(e) =>
                      updateCurrentTab({
                        request: { ...request, method: e.target.value },
                      })
                    }
                    className={`text-xs font-medium px-3 bg-transparent outline-none ${
                      isDark ? "text-white" : "text-gray-900"
                    }`}
                    style={{ minWidth: "80px" }}
                  >
                    {[
                      "GET",
                      "POST",
                      "PUT",
                      "PATCH",
                      "DELETE",
                      "HEAD",
                      "OPTIONS",
                    ].map((method) => (
                      <option key={method} value={method}>
                        {method}
                      </option>
                    ))}
                  </select>

                  {/* Divider */}
                  <div
                    className={`w-px h-6 self-center rounded-full ${
                      isDark ? "bg-gray-600" : "bg-gray-300"
                    }`}
                  ></div>

                  {/* URL INPUT */}
                  <input
                    type="text"
                    placeholder="https://api.example.com/endpoint"
                    value={request.url}
                    onChange={(e) =>
                      updateCurrentTab({
                        request: { ...request, url: e.target.value },
                      })
                    }
                    className={`flex-1 text-sm px-3 bg-transparent outline-none ${
                      isDark
                        ? "text-white placeholder-gray-400"
                        : "text-gray-900 placeholder-gray-500"
                    }`}
                  />
                </div>
              </div>

              {/* SEND BUTTON */}
              <div className="flex items-center gap-2">
                <Button
                  onClick={executeRequest}
                  disabled={!request.url || loading}
                  className={`h-10 sm:h-11 px-6 text-sm font-medium transition-all duration-200 ${
                    loading
                      ? "bg-gray-400 cursor-not-allowed"
                      : isDark
                      ? "bg-blue-600 hover:bg-blue-700"
                      : "bg-black hover:bg-gray-800"
                  } text-white rounded-md`}
                >
                  {loading ? (
                    <div className="flex items-center gap-2">
                      <Loader2 className="h-4 w-4 animate-spin" />
                      Sending...
                    </div>
                  ) : (
                    "Send"
                  )}
                </Button>
              </div>
            </div>
          </div>
        </div>

        {/* Request/Response Layout */}
        <div
          data-layout-container
          className={`flex-1 flex ${
            layoutMode === "single" ? "flex-col" : "flex-col lg:flex-row"
          } ${themeClasses.bg.primary} transition-colors duration-300 ${
            isDragging
              ? layoutMode === "single"
                ? "cursor-row-resize"
                : "cursor-col-resize"
              : ""
          }`}
        >
          {layoutMode === "split" ? (
            <>
              {/* Request Panel with dynamic width */}
              <div style={{ width: `${requestPanelWidth}%` }}>
                <RequestPanel request={request} setRequest={setRequest} />
              </div>

              {/* Horizontal Draggable Divider */}
              <div
                className="relative w-1 cursor-col-resize group"
                onMouseDown={handleMouseDown}
                title="Resize panels"
              >
                <div
                  className={`absolute left-1/2 transform -translate-x-1/2 w-px h-full bg-gray-200/60 dark:bg-gray-600 hover:bg-blue-500 ${
                    isDragging
                      ? "bg-blue-500"
                      : "transition-colors duration-200"
                  }`}
                />
              </div>

              {/* Response Panel with remaining width */}
              <div style={{ width: `${100 - requestPanelWidth}%` }}>
                <ResponsePanel
                  response={response}
                  loading={loading}
                  request={request}
                />
              </div>
            </>
          ) : (
            <>
              {/* Request Panel with dynamic height */}
              <div style={{ height: `${requestPanelHeight}%` }}>
                <RequestPanel request={request} setRequest={setRequest} />
              </div>

              {/* Vertical Draggable Divider */}
              <div
                className="relative h-1 cursor-row-resize group"
                onMouseDown={handleMouseDown}
                title="Resize panels"
              >
                <div
                  className={`absolute top-1/2 transform -translate-y-1/2 w-full h-px bg-gray-200/60 dark:bg-gray-600 hover:bg-blue-500 ${
                    isDragging
                      ? "bg-blue-500"
                      : "transition-colors duration-200"
                  }`}
                />
              </div>

              {/* Response Panel with remaining height */}
              <div style={{ height: `${100 - requestPanelHeight}%` }}>
                <ResponsePanel
                  response={response}
                  loading={loading}
                  request={request}
                />
              </div>
            </>
          )}
        </div>
      </div>

      {/* Create Environment Dialog */}
      <CreateEnvironmentModal
        open={createEnvironmentDialogOpen}
        onOpenChange={setCreateEnvironmentDialogOpen}
        onCreateEnvironment={handleCreateEnvironment}
      />

      {/* Add Variable Dialog */}
      <AddVariableModal
        open={addVariableDialogOpen}
        onOpenChange={setAddVariableDialogOpen}
        onAddVariable={handleSaveNewVariable}
        environmentId={selectedEnvironmentForVariable}
      />

      {/* Edit Variable Dialog */}
      <EditVariableModal
        open={editVariableDialogOpen}
        onOpenChange={setEditVariableDialogOpen}
        onEditVariable={handleSaveEditedVariable}
        environmentId={selectedEnvironmentForVariable}
        variableIndex={selectedVariableIndex}
        variable={
          environments[selectedEnvironmentForVariable]?.variables?.[
            selectedVariableIndex
          ]
        }
      />

      {/* Docs Generator Modal */}
      <DocGeneratorModal
        open={docsModalOpen}
        onOpenChange={(open) => {
          setDocsModalOpen(open);
          if (!open) {
            setSelectedCollectionForDocs(null);
          }
        }}
        collections={getCollectionsWithDocs()}
        preSelectedCollectionId={selectedCollectionForDocs}
        onGenerate={(docData) => {
          console.log("Generated docs with data:", docData);
          setDocsModalOpen(false);
          setSelectedCollectionForDocs(null);
        }}
      />

      {/* Settings Modal */}
      <SettingsModal
        open={settingsModalOpen}
        onOpenChange={setSettingsModalOpen}
      />

      {/* Create Collection Dialog */}
      <CreateCollectionModal
        open={createCollectionDialogOpen}
        onOpenChange={setCreateCollectionDialogOpen}
        onCreateCollection={handleCreateCollection}
      />

      {/* Save to Collection Modal */}
      <SaveToCollectionModal
        open={saveToCollectionModalOpen}
        onOpenChange={setSaveToCollectionModalOpen}
        collections={collections}
        onSaveToCollection={handleSaveToCollection}
      />
    </>
  );
}
