import {
  Share2,
  History,
  BookOpen,
  Check,
  Copy,
  PanelLeftOpen,
  PanelLeftClose,
  Zap,
  FolderOpen,
  Settings,
  Globe,
  Search,
  Plus,
  X,
  Moon,
  Sun,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Pencil,
  Send,
  Trash2,
  Loader2,
  MoreHorizontal,
  FileText,
  Edit,
  Upload,
  Download,
  FileUp,
  FileDown,
  Columns,
  SplitSquareHorizontal,
  Import,
} from "lucide-react";

// Sidebar menu items
export const sidebarMenuItems = [
  {
    id: "collections",
    icon: FolderOpen,
    label: "Collections",
    description: "Saved grouped requests",
  },
  {
    id: "history",
    icon: History,
    label: "History",
    description: "Past requests sent",
  },
  {
    id: "environments",
    icon: Globe,
    label: "Environments",
    description: "Manage variables like API keys, URLs, tokens",
  },
  {
    id: "documentation",
    icon: BookOpen,
    label: "Docs",
    description: "API Documentation",
  },
  {
    id: "trash",
    icon: Trash2,
    label: "Trash",
    description: "Deleted or outdated requests",
  },
];
